version: '2'

services:
    parser:
        image: golang:1.8.0
        volumes:
            - ./parser:/go/src/app
        working_dir: /go/src/app
        command: bash -c "go get; go run app.go"
        ports:
            - 6578:6578
        env_file:
            - .env

    # reader_api:
    #     image: microsoft/dotnet:1.0.0-preview2-sdk
    #     volumes:
    #         - ./reader_api:/app
    #     working_dir: /app
    #     command: bash -c "./startup.sh"
    #     ports:
    #         - 4999:4999

    # databaseServer:
    #     image: mysql:8
    #     env_file:
    #         - .env
    #     environment:
    #         TZ: ${TZ}
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #     expose:
    #         - 3306

    cron:
        image: microsoft/dotnet:1.0.0-preview2-sdk
        volumes:
            - ./cron:/app
        working_dir: /app
        command: bash -c "dotnet restore; dotnet run"
        links:
            - parser
        ports:
            - 5001:5001
