version: '2'

services:
    # parser:
    #     image: golang:1.8.0
    #     volumes:
    #         - ./parser:/go/src/app
    #     working_dir: /go/src/app
    #     command: bash -c "go get; go run app.go"
    #     env_file:
    #         - .env

  reader_api:
    image: microsoft/dotnet:latest
    volumes:
      - ./dotnet_api:/app
    working_dir: /app
    command: bash -c "dotnet rss_dotnet_api.dll"
    depends_on:
      - databaseServer
    ports:
      - 5000:5000


  databaseServer:
    image: mysql:8
    environment:
      TZ: Europe/Warsaw
      MYSQL_ROOT_PASSWORD: dbroot
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    expose:
      - 3306

    cron:
        image: microsoft/dotnet:1.0.0-preview2-sdk
        volumes:
            - ./cron:/app
        working_dir: /app
        command: bash -c "dotnet restore;sleep 20; dotnet run"
        links:
            - "reader_api"
        ports:
            - 5001:5001